#!/bin/sh
# Run from any directory. Generated bytes are owned by the KC3 exporter.
set -eu
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
binary=${KC3RTS_KC3S:-$root/.toolchain/kc3/kc3s/kc3s}
case "$binary" in /*) ;; *) binary="$PWD/$binary" ;; esac
runtime=$(dirname "$(dirname "$binary")")
export LD_LIBRARY_PATH="$runtime/libkc3:$runtime/lib/kc3/0.1${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
output="$root/web/src/game/generated/catalog.json"
temporary=$(mktemp)
trap 'rm -f "$temporary"' EXIT HUP INT TERM
(cd "$runtime" && "$binary" --load "$root/kc3/export.kc3" --quit) > "$temporary"
case "${1:-}" in
  --check) cmp "$temporary" "$output" || { echo 'Run sh scripts/export-content.sh to refresh the KC3 catalog.' >&2; exit 1; } ;;
  '') mkdir -p "$(dirname "$output")"; cp "$temporary" "$output" ;;
  *) echo 'Usage: scripts/export-content.sh [--check]' >&2; exit 2 ;;
esac
